# Generated by Django 5.1.5 on 2025-02-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_alter_tasks_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_code',
            field=models.TextField(default='DEFAULT_CODE', max_length=5000),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_dec',
            field=models.TextField(default='DEFAULT_DEC', max_length=300),
        ),
    ]
